# Site settings
title: 流浪诗人工作室
email: 137987751@qq.com
description: 流浪诗人工作室
baseurl: "/material-jekyll-theme"
url: "http://WeissWill.github.io"
fixedNav: 'true' # true or false
theme: purple # green, blue, orange, purple, grey
twitterUsername: WeissWill
githubUsername: WeissWill
dribbbleUsername:WeissWill
codepenUsername:WeissWill

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
